### PR TITLE
Pass EventType to AvailableTo factory method where needed

### PR DESCRIPTION
**Pull request by jdrieghe**
### Changed
- We now correctly use the EventType to determine what calendar date to use for AvailableTo

---
Ticket: https://jira.uitdatabank.be/browse/III-3242

### CODE REVIEW

**Comment by bertramakers** [comment]
Code changes look good 👍 
Maybe you can also add a test for this, or change the existing `it_handles_copy_event` test in the file you changed?

Also to remind ourselves how far we've come: In the past this would have required changes to two repositories. I'm still very happy that we can make a lot of the changes in a single repository now 🤩

**Comment by jdrieghe** [comment]
@bertramakers I added the missing test for the AvailableTo factory method.
I think the other part is already covered or the AvailableTo would not be properly set on the copied event.

**Comment by bertramakers** [comment]
How do you know that the logic you added to the projector to determine the event type is correct and it's not always passing `null` for example?

**Comment by jdrieghe** [comment]
@bertramakers Good point. Testing that will couple it to the specific use case but that's probably better than not having the test. Will add it.

**Comment by jdrieghe** [comment]
I'm sorry it took a bit longer. Had quite a busy schedule combined with some time off this week.

**Review by bertramakers — APPROVED** [review]
No problem at all @jdrieghe , if you're busy I'd rather have you take your time to polish it a few days later and make it as good as possible (in this case with extra tests), then that you'd rush to get it done a bit sooner. 👍

**Pull request merged**
