### PR TITLE
III-2973 - set calendarinfo on reports to small view

### PR DESCRIPTION
**Pull request by brampauwelyn**
### Changed
- Changed calendar view on reports to small, instead of large

### CODE REVIEW

**Comment by bertramakers** [comment]
Hey @brampauwelyn! Is there a reason the `composer.lock` file was updated with this change? I'm assuming this was an accident. Can you revert this please? Thanks!

**Comment by bertramakers** [comment]
@brampauwelyn thanks for taking the time to revert the `composer.lock` file. I noticed in the build output that some tests are failing now, but for some reason the build is still green. Can you fix these tests (should be pretty straightforward) while I check why the build was green with failing tests?

**Comment by bertramakers** [comment]
> while I check why the build was green with failing tests?

Should be fixed in this PR: https://github.com/cultuurnet/udb3-silex/pull/343

**Comment by jdrieghe** [comment]
Since it was fairly trivial, I quickly fixed the test here. Good to merge now 👍

**Pull request merged**
