### PR TITLE
III-3500 - Simplify purge command

### PR DESCRIPTION
**Pull request by jdrieghe**
### Changed
- Simplified implementation of purge command for read models. 
- Write models can no longer be purged.

---
Ticket: https://jira.uitdatabank.be/browse/III-3500

### CODE REVIEW

**Comment by jdrieghe** [comment]
I checked, all necessary read model tables are in the purge command's configuration right now. Nothing needed to be added.

**Review by bertramakers — APPROVED** [review]
Nice cleanup! 👍

**Comment by LucWollants** [comment]
Indeed nice cleanup. I wonder if everything can be moved to the `PurgeModelCommand`?
We only need a list of read model tables and iterate over them to do a truncate?

**Comment by jdrieghe** [comment]
@LucWollants if we don't need the special case for SQLite in the DBALPurgeService then it can be simplified even further like that, indeed.

**Comment by LucWollants** [comment]
I think we only run it when we want to replay and that is something we do manual on real MySQL data and not the SQLite test database.

**Comment by jdrieghe** [comment]
@LucWollants https://github.com/cultuurnet/udb3-silex/pull/659

**Pull request merged**
